/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Account {

  /**
   * Short description or biography of the user
   */
  bio?: string;

  /**
   * Date and time of account creation
   */
  createdAt?: string;

  /**
   * Full name of the user
   */
  fullName: string;

  /**
   * Unique identifier of the account
   */
  id?: string;

  /**
   * List of user's skills or tags
   */
  skills?: Array<string>;

  /**
   * Date and time of last account update
   */
  updatedAt?: string;

  /**
   * Unique username (login/handle)
   */
  username: string;

  /**
   * URL of the user's profile picture
   */
  userpicUrl?: string;
}
