/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema for creating a new account (ID is server-generated)
 */
export interface AccountCreate {

  /**
   * Short description or biography of the user
   */
  bio?: string;

  /**
   * Full name of the user
   */
  fullName: string;

  /**
   * List of user's skills or tags
   */
  skills?: Array<string>;

  /**
   * Unique username (login/handle)
   */
  username: string;

  /**
   * URL of the user's profile picture
   */
  userpicUrl?: string;
}
