/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Schema for partially updating an account (all fields are optional)
 */
export interface AccountUpdate {

  /**
   * Short description or biography of the user
   */
  bio?: string;

  /**
   * Full name of the user
   */
  fullName?: string;

  /**
   * List of user's skills or tags
   */
  skills?: Array<string>;

  /**
   * Unique username (login/handle)
   */
  username?: string;

  /**
   * URL of the user's profile picture
   */
  userpicUrl?: string;
}
