/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ErrorResponse {

  /**
   * Error code (optional)
   */
  code?: number;

  /**
   * Error message
   */
  message?: string;
}
